### ISSUE TITLE
[Feature] Auth0 Integration

### ISSUE THREAD

**Issue by jahnzeb-bastaki** [UTDallasEPICS/Soccer-Robot-Web#34]
**Feature Description**
Basic Auth0 integration within the website.

**Requirements**
- [ ]  Auth0 Login
- [ ] Store User in Database after Auth0 if new user
- [ ] Retrieve existing user when Auth0 Login is invoked

**Additional context**
- None at the moment, may change

**Comment by CrazEpic** [comment]
done
